//
//  DonutStyleKit.swift
//  DonutSelfie
//
//  Created by Arjun Sarode on 10/24/14.
//  Copyright (c) 2014 SprinklesAndCo. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class DonutStyleKit : NSObject {

    //// Initialization

    override class func load() {
    }

    //// Drawing Methods

    class func drawLogo() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.988, blue: 0.940, alpha: 1.000)
        let color3 = UIColor(red: 0.387, green: 0.252, blue: 0.000, alpha: 1.000)
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)
        let color5 = UIColor(red: 0.486, green: 0.853, blue: 1.000, alpha: 1.000)
        let color6 = UIColor(red: 0.721, green: 0.975, blue: 1.000, alpha: 1.000)
        let color7 = UIColor(red: 0.444, green: 0.704, blue: 1.000, alpha: 1.000)

        //// Group
        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(40.92, 40.75))
        bezierPath.addCurveToPoint(CGPointMake(40.92, 58.08), controlPoint1: CGPointMake(36.14, 45.54), controlPoint2: CGPointMake(36.14, 53.29))
        bezierPath.addCurveToPoint(CGPointMake(58.25, 58.08), controlPoint1: CGPointMake(45.71, 62.86), controlPoint2: CGPointMake(53.46, 62.86))
        bezierPath.addCurveToPoint(CGPointMake(58.25, 40.75), controlPoint1: CGPointMake(63.03, 53.29), controlPoint2: CGPointMake(63.03, 45.54))
        bezierPath.addCurveToPoint(CGPointMake(40.92, 40.75), controlPoint1: CGPointMake(53.46, 35.97), controlPoint2: CGPointMake(45.71, 35.97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(78.7, 20.3))
        bezierPath.addCurveToPoint(CGPointMake(78.7, 79.7), controlPoint1: CGPointMake(95.1, 36.7), controlPoint2: CGPointMake(95.1, 63.3))
        bezierPath.addCurveToPoint(CGPointMake(19.3, 79.7), controlPoint1: CGPointMake(62.3, 96.1), controlPoint2: CGPointMake(35.7, 96.1))
        bezierPath.addCurveToPoint(CGPointMake(19.3, 20.3), controlPoint1: CGPointMake(2.9, 63.3), controlPoint2: CGPointMake(2.9, 36.7))
        bezierPath.addCurveToPoint(CGPointMake(78.7, 20.3), controlPoint1: CGPointMake(35.7, 3.9), controlPoint2: CGPointMake(62.3, 3.9))
        bezierPath.closePath()
        color3.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(37.33, 40.67))
        bezier2Path.addCurveToPoint(CGPointMake(40.83, 60.5), controlPoint1: CGPointMake(32.55, 45.45), controlPoint2: CGPointMake(36.05, 55.72))
        bezier2Path.addCurveToPoint(CGPointMake(61.83, 60.5), controlPoint1: CGPointMake(45.62, 65.28), controlPoint2: CGPointMake(57.05, 65.28))
        bezier2Path.addCurveToPoint(CGPointMake(58.33, 37.17), controlPoint1: CGPointMake(66.62, 55.72), controlPoint2: CGPointMake(63.12, 41.95))
        bezier2Path.addCurveToPoint(CGPointMake(37.33, 40.67), controlPoint1: CGPointMake(53.55, 32.38), controlPoint2: CGPointMake(42.12, 35.88))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(45.5, 10.33))
        bezier2Path.addCurveToPoint(CGPointMake(78.7, 20.3), controlPoint1: CGPointMake(56, 10.33), controlPoint2: CGPointMake(70.74, 12.34))
        bezier2Path.addCurveToPoint(CGPointMake(88.67, 52.33), controlPoint1: CGPointMake(87.02, 28.62), controlPoint2: CGPointMake(88.78, 41.43))
        bezier2Path.addCurveToPoint(CGPointMake(78.17, 79.17), controlPoint1: CGPointMake(88.55, 62.93), controlPoint2: CGPointMake(86.25, 71.08))
        bezier2Path.addCurveToPoint(CGPointMake(51.33, 90.83), controlPoint1: CGPointMake(70.65, 86.68), controlPoint2: CGPointMake(61.17, 90.21))
        bezier2Path.addCurveToPoint(CGPointMake(21, 79.17), controlPoint1: CGPointMake(39.71, 91.57), controlPoint2: CGPointMake(29.88, 88.05))
        bezier2Path.addCurveToPoint(CGPointMake(8.17, 48.83), controlPoint1: CGPointMake(13.26, 71.43), controlPoint2: CGPointMake(8.17, 67.5))
        bezier2Path.addCurveToPoint(CGPointMake(19.3, 20.3), controlPoint1: CGPointMake(8.17, 44.17), controlPoint2: CGPointMake(13.62, 25.98))
        bezier2Path.addCurveToPoint(CGPointMake(45.5, 10.33), controlPoint1: CGPointMake(23.48, 16.12), controlPoint2: CGPointMake(35.2, 10.33))
        bezier2Path.closePath()
        color.setFill()
        bezier2Path.fill()


        //// Bezier 8 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 70.19, 35.26)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier8Path = UIBezierPath()
        bezier8Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier8Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier8Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier8Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier8Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier8Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier8Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier8Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier8Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier8Path.closePath()
        color6.setFill()
        bezier8Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 3 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 60.86, 22.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier3Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier3Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier3Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier3Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier3Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier3Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier3Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier3Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier3Path.closePath()
        color5.setFill()
        bezier3Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 4 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 60.86, 79.59)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier4Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier4Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier4Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier4Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier4Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier4Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier4Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier4Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier4Path.closePath()
        color4.setFill()
        bezier4Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 5 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 43.36, 29.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier5Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier5Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier5Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier5Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier5Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier5Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier5Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier5Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier5Path.closePath()
        color4.setFill()
        bezier5Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 6 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 73.69, 49.26)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier6Path = UIBezierPath()
        bezier6Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier6Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier6Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier6Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier6Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier6Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier6Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier6Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier6Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier6Path.closePath()
        color4.setFill()
        bezier6Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 7 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 32.86, 15.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier7Path = UIBezierPath()
        bezier7Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier7Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier7Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier7Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier7Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier7Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier7Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier7Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier7Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier7Path.closePath()
        color5.setFill()
        bezier7Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 10 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 79.52, 42.26)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier10Path = UIBezierPath()
        bezier10Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier10Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier10Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier10Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier10Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier10Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier10Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier10Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier10Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier10Path.closePath()
        color7.setFill()
        bezier10Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 11 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 23.52, 71.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier11Path = UIBezierPath()
        bezier11Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier11Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier11Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier11Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier11Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier11Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier11Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier11Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier11Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier11Path.closePath()
        color7.setFill()
        bezier11Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 12 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 76.02, 76.09)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier12Path = UIBezierPath()
        bezier12Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier12Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier12Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier12Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier12Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier12Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier12Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier12Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier12Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier12Path.closePath()
        color7.setFill()
        bezier12Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 13 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 58.52, 15.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier13Path = UIBezierPath()
        bezier13Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier13Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier13Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier13Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier13Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier13Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier13Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier13Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier13Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier13Path.closePath()
        color6.setFill()
        bezier13Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 14 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 21.19, 35.26)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier14Path = UIBezierPath()
        bezier14Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier14Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier14Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier14Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier14Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier14Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier14Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier14Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier14Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier14Path.closePath()
        color7.setFill()
        bezier14Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 15 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 17.69, 50.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier15Path = UIBezierPath()
        bezier15Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier15Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier15Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier15Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier15Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier15Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier15Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier15Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier15Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier15Path.closePath()
        color5.setFill()
        bezier15Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 16 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 29.36, 60.93)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier16Path = UIBezierPath()
        bezier16Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier16Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier16Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier16Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier16Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier16Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier16Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier16Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier16Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier16Path.closePath()
        color4.setFill()
        bezier16Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 17 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 41.02, 81.93)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier17Path = UIBezierPath()
        bezier17Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier17Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier17Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier17Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier17Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier17Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier17Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier17Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier17Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier17Path.closePath()
        color7.setFill()
        bezier17Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 18 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 73.69, 28.26)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier18Path = UIBezierPath()
        bezier18Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier18Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier18Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier18Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier18Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier18Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier18Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier18Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier18Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier18Path.closePath()
        color4.setFill()
        bezier18Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 19 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 27.02, 24.76)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier19Path = UIBezierPath()
        bezier19Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier19Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier19Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier19Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier19Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier19Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier19Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier19Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier19Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier19Path.closePath()
        color6.setFill()
        bezier19Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 20 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 56.19, 71.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier20Path = UIBezierPath()
        bezier20Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier20Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier20Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier20Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier20Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier20Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier20Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier20Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier20Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier20Path.closePath()
        color6.setFill()
        bezier20Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 21 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 38.69, 72.59)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier21Path = UIBezierPath()
        bezier21Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier21Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier21Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier21Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier21Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier21Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier21Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier21Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier21Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier21Path.closePath()
        color6.setFill()
        bezier21Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 22 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 44.52, 18.93)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier22Path = UIBezierPath()
        bezier22Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier22Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier22Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier22Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier22Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier22Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier22Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier22Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier22Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier22Path.closePath()
        color7.setFill()
        bezier22Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 23 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 29.36, 43.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier23Path = UIBezierPath()
        bezier23Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier23Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier23Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier23Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier23Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier23Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier23Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier23Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier23Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier23Path.closePath()
        color7.setFill()
        bezier23Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 24 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 70.19, 69.09)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier24Path = UIBezierPath()
        bezier24Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier24Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier24Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier24Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier24Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier24Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier24Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier24Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier24Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier24Path.closePath()
        color5.setFill()
        bezier24Path.fill()

        CGContextRestoreGState(context)


        //// Bezier 25 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 81.86, 57.43)
//        CGContextRotateCTM(context, 67.68 * M_PI / 180)

        var bezier25Path = UIBezierPath()
        bezier25Path.moveToPoint(CGPointMake(0.57, -2.77))
        bezier25Path.addCurveToPoint(CGPointMake(0.81, -2.06), controlPoint1: CGPointMake(0.73, -2.57), controlPoint2: CGPointMake(0.81, -2.31))
        bezier25Path.addLineToPoint(CGPointMake(0.81, 2.06))
        bezier25Path.addCurveToPoint(CGPointMake(0.57, 2.77), controlPoint1: CGPointMake(0.81, 2.31), controlPoint2: CGPointMake(0.73, 2.57))
        bezier25Path.addCurveToPoint(CGPointMake(-0.57, 2.77), controlPoint1: CGPointMake(0.25, 3.16), controlPoint2: CGPointMake(-0.25, 3.16))
        bezier25Path.addCurveToPoint(CGPointMake(-0.81, 2.06), controlPoint1: CGPointMake(-0.73, 2.57), controlPoint2: CGPointMake(-0.81, 2.31))
        bezier25Path.addLineToPoint(CGPointMake(-0.81, -2.06))
        bezier25Path.addCurveToPoint(CGPointMake(-0.57, -2.77), controlPoint1: CGPointMake(-0.81, -2.31), controlPoint2: CGPointMake(-0.73, -2.57))
        bezier25Path.addCurveToPoint(CGPointMake(0.57, -2.77), controlPoint1: CGPointMake(-0.25, -3.16), controlPoint2: CGPointMake(0.25, -3.16))
        bezier25Path.closePath()
        color6.setFill()
        bezier25Path.fill()

        CGContextRestoreGState(context)
    }

    class func drawAddButton(buttonRadius: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.988, blue: 0.940, alpha: 1.000)
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)

        //// Shadow Declarations
        let shadow2 = UIColor.blackColor().colorWithAlphaComponent(0.29)
        let shadow2Offset = CGSizeMake(0.1, 1.6)
        let shadow2BlurRadius: CGFloat = 5

        //// Group
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow2Offset, shadow2BlurRadius, shadow2.CGColor)
        CGContextBeginTransparencyLayer(context, nil)


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(8, 8, 70, 70), cornerRadius: buttonRadius)
        color4.setFill()
        rectanglePath.fill()
        color4.setStroke()
        rectanglePath.lineWidth = 5
        rectanglePath.stroke()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(45.86, 27.85))
        bezierPath.addCurveToPoint(CGPointMake(46.9, 30.17), controlPoint1: CGPointMake(46.51, 28.49), controlPoint2: CGPointMake(46.85, 29.33))
        bezierPath.addCurveToPoint(CGPointMake(46.9, 40.08), controlPoint1: CGPointMake(46.9, 30.17), controlPoint2: CGPointMake(46.9, 34.75))
        bezierPath.addCurveToPoint(CGPointMake(56.48, 40.08), controlPoint1: CGPointMake(52.08, 40.08), controlPoint2: CGPointMake(56.48, 40.08))
        bezierPath.addCurveToPoint(CGPointMake(59.19, 41.01), controlPoint1: CGPointMake(57.46, 40.04), controlPoint2: CGPointMake(58.45, 40.35))
        bezierPath.addCurveToPoint(CGPointMake(59.19, 45.51), controlPoint1: CGPointMake(60.59, 42.25), controlPoint2: CGPointMake(60.59, 44.27))
        bezierPath.addCurveToPoint(CGPointMake(56.48, 46.44), controlPoint1: CGPointMake(58.45, 46.17), controlPoint2: CGPointMake(57.46, 46.48))
        bezierPath.addCurveToPoint(CGPointMake(46.9, 46.44), controlPoint1: CGPointMake(56.48, 46.44), controlPoint2: CGPointMake(52.08, 46.44))
        bezierPath.addCurveToPoint(CGPointMake(46.9, 56.16), controlPoint1: CGPointMake(46.9, 51.14), controlPoint2: CGPointMake(46.9, 55.25))
        bezierPath.addCurveToPoint(CGPointMake(46.9, 56.35), controlPoint1: CGPointMake(46.9, 56.29), controlPoint2: CGPointMake(46.9, 56.35))
        bezierPath.addCurveToPoint(CGPointMake(45.86, 58.68), controlPoint1: CGPointMake(46.85, 57.2), controlPoint2: CGPointMake(46.51, 58.03))
        bezierPath.addCurveToPoint(CGPointMake(40.81, 58.68), controlPoint1: CGPointMake(44.46, 60.06), controlPoint2: CGPointMake(42.2, 60.06))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 56.35), controlPoint1: CGPointMake(40.16, 58.03), controlPoint2: CGPointMake(39.82, 57.2))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 56.16), controlPoint1: CGPointMake(39.77, 56.35), controlPoint2: CGPointMake(39.77, 56.29))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 46.44), controlPoint1: CGPointMake(39.77, 55.25), controlPoint2: CGPointMake(39.77, 51.14))
        bezierPath.addCurveToPoint(CGPointMake(30.56, 46.44), controlPoint1: CGPointMake(34.75, 46.44), controlPoint2: CGPointMake(30.56, 46.44))
        bezierPath.addCurveToPoint(CGPointMake(27.85, 45.51), controlPoint1: CGPointMake(29.59, 46.48), controlPoint2: CGPointMake(28.6, 46.17))
        bezierPath.addCurveToPoint(CGPointMake(27.85, 41.01), controlPoint1: CGPointMake(26.46, 44.27), controlPoint2: CGPointMake(26.46, 42.25))
        bezierPath.addCurveToPoint(CGPointMake(30.56, 40.09), controlPoint1: CGPointMake(28.6, 40.35), controlPoint2: CGPointMake(29.59, 40.04))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 40.09), controlPoint1: CGPointMake(30.56, 40.09), controlPoint2: CGPointMake(34.75, 40.09))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 30.36), controlPoint1: CGPointMake(39.77, 35.39), controlPoint2: CGPointMake(39.77, 31.27))
        bezierPath.addCurveToPoint(CGPointMake(39.77, 30.17), controlPoint1: CGPointMake(39.77, 30.24), controlPoint2: CGPointMake(39.77, 30.17))
        bezierPath.addCurveToPoint(CGPointMake(40.81, 27.85), controlPoint1: CGPointMake(39.82, 29.33), controlPoint2: CGPointMake(40.16, 28.49))
        bezierPath.addCurveToPoint(CGPointMake(45.86, 27.85), controlPoint1: CGPointMake(42.2, 26.46), controlPoint2: CGPointMake(44.46, 26.46))
        bezierPath.closePath()
        color.setFill()
        bezierPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    class func drawPlayButton() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.988, blue: 0.940, alpha: 1.000)
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)
        let color7 = UIColor(red: 0.444, green: 0.704, blue: 1.000, alpha: 1.000)

        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [color7.CGColor, color4.CGColor], [0, 1])

        //// Shadow Declarations
        let shadow2 = UIColor.blackColor().colorWithAlphaComponent(0.29)
        let shadow2Offset = CGSizeMake(0.1, 1.6)
        let shadow2BlurRadius: CGFloat = 5

        //// Group
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow2Offset, shadow2BlurRadius, shadow2.CGColor)
        CGContextBeginTransparencyLayer(context, nil)


        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(5, 5, 75, 75))
        CGContextSaveGState(context)
        ovalPath.addClip()
        CGContextDrawLinearGradient(context, gradient, CGPointMake(42.5, 5), CGPointMake(42.5, 80), 0)
        CGContextRestoreGState(context)


        //// Polygon Drawing
        var polygonPath = UIBezierPath()
        polygonPath.moveToPoint(CGPointMake(62.47, 42.01))
        polygonPath.addLineToPoint(CGPointMake(33.25, 58.88))
        polygonPath.addLineToPoint(CGPointMake(33.25, 25.14))
        polygonPath.addLineToPoint(CGPointMake(62.47, 42.01))
        polygonPath.closePath()
        polygonPath.lineCapStyle = kCGLineCapRound;

        polygonPath.lineJoinStyle = kCGLineJoinRound;

        color.setFill()
        polygonPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    class func drawBackButton() {
        //// Color Declarations
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(12.27, 25.02))
        bezier2Path.addCurveToPoint(CGPointMake(3, 15.26), controlPoint1: CGPointMake(3, 15.26), controlPoint2: CGPointMake(3, 15.26))
        bezier2Path.addLineToPoint(CGPointMake(12.27, 5.5))
        bezier2Path.addLineToPoint(CGPointMake(12.27, 5.5))
        bezier2Path.moveToPoint(CGPointMake(3, 15.26))
        bezier2Path.addLineToPoint(CGPointMake(27, 15.26))
        bezier2Path.lineCapStyle = kCGLineCapRound;

        bezier2Path.lineJoinStyle = kCGLineJoinRound;

        color4.setStroke()
        bezier2Path.lineWidth = 5
        bezier2Path.stroke()
    }

    class func drawContinueButton(buttonRadius: CGFloat) {
        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.988, blue: 0.940, alpha: 1.000)
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)

        //// Group
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(4, 3, 58.5, 32), cornerRadius: buttonRadius)
        color.setFill()
        rectanglePath.fill()
        color4.setStroke()
        rectanglePath.lineWidth = 5
        rectanglePath.stroke()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(40.5, 10.5))
        bezier3Path.addLineToPoint(CGPointMake(49.5, 19.5))
        bezier3Path.addLineToPoint(CGPointMake(40.5, 28.5))
        bezier3Path.moveToPoint(CGPointMake(49.5, 19.5))
        bezier3Path.addLineToPoint(CGPointMake(16.5, 19.5))
        bezier3Path.lineCapStyle = kCGLineCapRound;

        bezier3Path.lineJoinStyle = kCGLineJoinRound;

        color4.setStroke()
        bezier3Path.lineWidth = 5
        bezier3Path.stroke()
    }

    class func drawSecondaryAddButton(buttonRadius: CGFloat) {
        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.988, blue: 0.940, alpha: 1.000)
        let color4 = UIColor(red: 0.253, green: 0.691, blue: 1.000, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(5, 5, 100, 100), cornerRadius: buttonRadius)
        color.setFill()
        rectanglePath.fill()
        color4.setStroke()
        rectanglePath.lineWidth = 5
        rectanglePath.stroke()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(59.08, 33.35))
        bezierPath.addCurveToPoint(CGPointMake(60.57, 36.67), controlPoint1: CGPointMake(60.01, 34.28), controlPoint2: CGPointMake(60.51, 35.47))
        bezierPath.addCurveToPoint(CGPointMake(60.57, 50.83), controlPoint1: CGPointMake(60.57, 36.67), controlPoint2: CGPointMake(60.57, 43.22))
        bezierPath.addCurveToPoint(CGPointMake(74.26, 50.83), controlPoint1: CGPointMake(67.97, 50.83), controlPoint2: CGPointMake(74.26, 50.83))
        bezierPath.addCurveToPoint(CGPointMake(78.13, 52.16), controlPoint1: CGPointMake(75.65, 50.77), controlPoint2: CGPointMake(77.07, 51.21))
        bezierPath.addCurveToPoint(CGPointMake(78.13, 58.58), controlPoint1: CGPointMake(80.12, 53.94), controlPoint2: CGPointMake(80.12, 56.81))
        bezierPath.addCurveToPoint(CGPointMake(74.26, 59.91), controlPoint1: CGPointMake(77.07, 59.53), controlPoint2: CGPointMake(75.65, 59.97))
        bezierPath.addCurveToPoint(CGPointMake(60.58, 59.91), controlPoint1: CGPointMake(74.26, 59.91), controlPoint2: CGPointMake(67.97, 59.91))
        bezierPath.addCurveToPoint(CGPointMake(60.58, 73.81), controlPoint1: CGPointMake(60.58, 66.62), controlPoint2: CGPointMake(60.58, 72.5))
        bezierPath.addCurveToPoint(CGPointMake(60.58, 74.07), controlPoint1: CGPointMake(60.58, 73.98), controlPoint2: CGPointMake(60.58, 74.07))
        bezierPath.addCurveToPoint(CGPointMake(59.08, 77.39), controlPoint1: CGPointMake(60.51, 75.28), controlPoint2: CGPointMake(60.01, 76.47))
        bezierPath.addCurveToPoint(CGPointMake(51.87, 77.39), controlPoint1: CGPointMake(57.09, 79.38), controlPoint2: CGPointMake(53.86, 79.38))
        bezierPath.addCurveToPoint(CGPointMake(50.39, 74.07), controlPoint1: CGPointMake(50.95, 76.47), controlPoint2: CGPointMake(50.45, 75.28))
        bezierPath.addCurveToPoint(CGPointMake(50.38, 73.81), controlPoint1: CGPointMake(50.38, 74.07), controlPoint2: CGPointMake(50.38, 73.98))
        bezierPath.addCurveToPoint(CGPointMake(50.38, 59.91), controlPoint1: CGPointMake(50.38, 72.5), controlPoint2: CGPointMake(50.38, 66.62))
        bezierPath.addCurveToPoint(CGPointMake(37.23, 59.91), controlPoint1: CGPointMake(43.22, 59.91), controlPoint2: CGPointMake(37.23, 59.91))
        bezierPath.addCurveToPoint(CGPointMake(33.36, 58.58), controlPoint1: CGPointMake(35.84, 59.97), controlPoint2: CGPointMake(34.42, 59.53))
        bezierPath.addCurveToPoint(CGPointMake(33.36, 52.16), controlPoint1: CGPointMake(31.37, 56.81), controlPoint2: CGPointMake(31.37, 53.94))
        bezierPath.addCurveToPoint(CGPointMake(37.23, 50.84), controlPoint1: CGPointMake(34.42, 51.21), controlPoint2: CGPointMake(35.84, 50.77))
        bezierPath.addCurveToPoint(CGPointMake(50.38, 50.84), controlPoint1: CGPointMake(37.23, 50.84), controlPoint2: CGPointMake(43.22, 50.84))
        bezierPath.addCurveToPoint(CGPointMake(50.38, 36.94), controlPoint1: CGPointMake(50.38, 44.12), controlPoint2: CGPointMake(50.38, 38.24))
        bezierPath.addCurveToPoint(CGPointMake(50.38, 36.67), controlPoint1: CGPointMake(50.38, 36.77), controlPoint2: CGPointMake(50.38, 36.67))
        bezierPath.addCurveToPoint(CGPointMake(51.87, 33.35), controlPoint1: CGPointMake(50.45, 35.47), controlPoint2: CGPointMake(50.95, 34.28))
        bezierPath.addCurveToPoint(CGPointMake(59.08, 33.35), controlPoint1: CGPointMake(53.86, 31.37), controlPoint2: CGPointMake(57.09, 31.37))
        bezierPath.closePath()
        color4.setFill()
        bezierPath.fill()
    }

    class func drawCanvas2() {
    }

}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
